### ISSUE TITLE
Code Block

### ISSUE THREAD

**Issue by liangchuxin** [khparry/typora-theme-mediumlike#1]
Hello I love your theme soooooo much. However in the theme, code blocks look like this:
![image](https://user-images.githubusercontent.com/35217053/77766890-36267600-707b-11ea-81e3-256ce85b1912.png)
Is there a way to get rid of the darker gray color within the light gray background? Thanks!

**Comment by ardianta** [comment]
@liangchuxin just add this style before `.md-fences` class:

```css
.cm-s-inner {
	background: none !important;
}
```
